image:
  repository: https://hub.docker.com/r/neo9sas/container-registry-operator
  tag: latest
deployment:
  annotations:
    reloader.stakater.com/auto: 'true'
global:
  env: application
  istio:
    enabled: false
service:
  port: 8080
  targetPort: 8080
ingress:
  enabled: false
resources:
  requests:
    cpu: 25m
    memory: 265M
  limits:
    cpu: 85m
    memory: 300M
pod:
  replicas: 1

serviceAccount:
  create: true
  name: 'container-registry-operator-sa'

clusterrole:
  enabled: true
  autoBindClusteRole: true
  rules:
    - apiGroups:
        - neo9.io
      resources:
        - container-registries-cleanupjob
        - container-registries
        - container-registries-cleanupjob/status
        - container-registries/status
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch

    - apiGroups:
        - ''
      resources:
        - secrets
        - configmaps
        - serviceaccounts
        - namespaces
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch

    - apiGroups:
        - batch
      resources:
        - cronjobs
      verbs:
        - create
        - delete
        - get
        - list
        - patch
        - update
        - watch
