const CONTAINER_REGISTRY_GROUP = 'neo9.io'
const CONTAINER_REGISTRY_VERSION = 'v1'
const NAMESPACE = 'container-registry-operator'
const CONTAINER_REGISTRIES = 'container-registries'
const CONTAINER_REGISTRIES_CLEANUP_JOB = 'container-registries-cleanupjob'

export { CONTAINER_REGISTRY_GROUP, CONTAINER_REGISTRY_VERSION, NAMESPACE, CONTAINER_REGISTRIES, CONTAINER_REGISTRIES_CLEANUP_JOB }
